defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
        author: "Jane Bloggs"
    - scope:
        path: ""
        type: "pages"
      values:
        layout: "default"
timezone: Australia/Brisbane

collections:
    publications: